version: "3"

services:
  db:
    ports:
      - 5432:5432
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift
